<a href="https://colab.research.google.com/github/AndreiMatosha/ML-Basic/blob/main/homework_07/homework_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [3]:
arr = np.zeros(10)
arr[4] = 1
arr_2d = arr.reshape(2, 5)
arr_2d

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [8]:
arr = np.random.randint(low=10, high=50, size=20, dtype=int)
reversed_arr = arr[::-1]
even_arr = reversed_arr[reversed_arr%2 == 0]
print('Array: ', arr)
print('Reversed Array', reversed_arr)
print('Even Elements of Array', even_arr)

Array:  [21 21 16 20 16 48 14 30 12 31 37 37 24 35 20 13 19 45 38 48]
Reversed Array [48 38 45 19 13 20 35 24 37 37 31 12 30 14 48 16 20 16 21 21]
Even Elements of Array [48 38 20 24 12 30 14 48 16 20 16]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [9]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [10]:
arr = np.random.rand(4, 3, 2)

min_value = np.min(arr)
max_value = np.max(arr)

print("Min value: ", min_value)
print("Max value: ", max_value)

Min value:  0.07123148564924264
Max value:  0.9857377967927793


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение.

In [13]:
arr_1 = np.random.rand(6, 4)
arr_2 = np.random.rand(4, 3)
arr_mult = arr_1 @ arr_2
arr_mult

array([[1.76958803, 1.40213357, 1.21209844],
       [0.67169098, 0.56912466, 0.3518356 ],
       [1.78921875, 1.55002329, 1.21487043],
       [1.49602533, 1.27658005, 0.96369692],
       [1.91107465, 1.6973834 , 1.25670084],
       [1.90016978, 1.66793484, 1.35996274]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [14]:
arr = np.random.rand(7, 7)
print(arr)
mean_value = np.mean(arr)
std_value = np.std(arr)
# Нормализуем массив
normalized_arr = (arr - mean_value) / std_value
print(normalized_arr)

[[0.82112848 0.62607215 0.34564633 0.54410509 0.60992671 0.78540608
  0.60115863]
 [0.6597685  0.18039208 0.03070408 0.92679632 0.45878362 0.39274986
  0.22953008]
 [0.49368138 0.33322103 0.5971904  0.85229822 0.12570949 0.60699137
  0.29909096]
 [0.30043973 0.56397515 0.5420623  0.36381162 0.79725755 0.31103811
  0.17076798]
 [0.21272541 0.00105257 0.67836667 0.81182396 0.59347612 0.23104087
  0.12483514]
 [0.12934483 0.91009489 0.8611847  0.57845516 0.64605804 0.13800887
  0.20728945]
 [0.00689573 0.46512272 0.29038059 0.19083494 0.93436447 0.87193425
  0.210866  ]]
[[ 1.32239436  0.60309472 -0.43101778  0.30082881  0.54355597  1.19066261
   0.51122236]
 [ 0.72735509 -1.04041774 -1.59241483  1.71206042 -0.01380697 -0.2573164
  -0.85921398]
 [ 0.11488379 -0.47683796  0.4965889   1.43733747 -1.24206804  0.53273147
  -0.60269773]
 [-0.59772394  0.37410267  0.29329574 -0.36403055  1.23436671 -0.55864081
  -1.07590805]
 [-0.92118371 -1.70175921  0.79593863  1.28808252  0.48289194 -0.85364

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ