<a href="https://colab.research.google.com/github/AndreiMatosha/ML-Basic/blob/main/homework_07/homework_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [3]:
arr = np.zeros(10)
arr[4] = 1
arr_2d = arr.reshape(2, 5)
arr_2d

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [8]:
arr = np.random.randint(low=10, high=50, size=20, dtype=int)
reversed_arr = arr[::-1]
even_arr = reversed_arr[reversed_arr%2 == 0]
print('Array: ', arr)
print('Reversed Array', reversed_arr)
print('Even Elements of Array', even_arr)

Array:  [21 21 16 20 16 48 14 30 12 31 37 37 24 35 20 13 19 45 38 48]
Reversed Array [48 38 45 19 13 20 35 24 37 37 31 12 30 14 48 16 20 16 21 21]
Even Elements of Array [48 38 20 24 12 30 14 48 16 20 16]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [9]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [10]:
arr = np.random.rand(4, 3, 2)

min_value = np.min(arr)
max_value = np.max(arr)

print("Min value: ", min_value)
print("Max value: ", max_value)

Min value:  0.07123148564924264
Max value:  0.9857377967927793


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение.

In [13]:
arr_1 = np.random.rand(6, 4)
arr_2 = np.random.rand(4, 3)
arr_mult = arr_1 @ arr_2
arr_mult

array([[1.76958803, 1.40213357, 1.21209844],
       [0.67169098, 0.56912466, 0.3518356 ],
       [1.78921875, 1.55002329, 1.21487043],
       [1.49602533, 1.27658005, 0.96369692],
       [1.91107465, 1.6973834 , 1.25670084],
       [1.90016978, 1.66793484, 1.35996274]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [14]:
arr = np.random.rand(7, 7)
print(arr)
mean_value = np.mean(arr)
std_value = np.std(arr)
# Нормализуем массив
normalized_arr = (arr - mean_value) / std_value
print(normalized_arr)

[[0.82112848 0.62607215 0.34564633 0.54410509 0.60992671 0.78540608
  0.60115863]
 [0.6597685  0.18039208 0.03070408 0.92679632 0.45878362 0.39274986
  0.22953008]
 [0.49368138 0.33322103 0.5971904  0.85229822 0.12570949 0.60699137
  0.29909096]
 [0.30043973 0.56397515 0.5420623  0.36381162 0.79725755 0.31103811
  0.17076798]
 [0.21272541 0.00105257 0.67836667 0.81182396 0.59347612 0.23104087
  0.12483514]
 [0.12934483 0.91009489 0.8611847  0.57845516 0.64605804 0.13800887
  0.20728945]
 [0.00689573 0.46512272 0.29038059 0.19083494 0.93436447 0.87193425
  0.210866  ]]
[[ 1.32239436  0.60309472 -0.43101778  0.30082881  0.54355597  1.19066261
   0.51122236]
 [ 0.72735509 -1.04041774 -1.59241483  1.71206042 -0.01380697 -0.2573164
  -0.85921398]
 [ 0.11488379 -0.47683796  0.4965889   1.43733747 -1.24206804  0.53273147
  -0.60269773]
 [-0.59772394  0.37410267  0.29329574 -0.36403055  1.23436671 -0.55864081
  -1.07590805]
 [-0.92118371 -1.70175921  0.79593863  1.28808252  0.48289194 -0.85364

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [30]:
import pandas as pd
import seaborn as sns
import matplotlib

### Загрузите датасет Tips из набора датасетов seaborn

In [31]:
tips = sns.load_dataset('tips')

### Посмотрите на первые 5 строчек

In [32]:
print(tips.head(n=5))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


### Узнайте сколько всего строчек и колонок в данных

In [33]:
tips.shape

(244, 7)

### Проверьте есть ли пропуски в данных

In [34]:
tips.isna().sum().sum()

np.int64(0)

### Посмотрите на распределение числовых признаков

In [35]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Найдите максимальное значение 'total_bill'

In [36]:
tips['total_bill'].max()

50.81

### Найдите количество курящих людей

In [37]:
tips[tips['smoker'] == 'Yes'].shape[0]

93

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [38]:
tips.groupby('day', observed=True)['total_bill'].mean()

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [39]:
print(tips.groupby('sex', observed=True)['tip'].mean())

print(tips[tips['total_bill'] > tips['total_bill'].median()])

sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64
     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[122 rows x 7 columns]


### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [42]:
tips['smoker']  = tips['smoker'].map({'No': 0, 'Yes': 1})
print(tips)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female      0   Sun  Dinner     2
1         10.34  1.66    Male      0   Sun  Dinner     3
2         21.01  3.50    Male      0   Sun  Dinner     3
3         23.68  3.31    Male      0   Sun  Dinner     2
4         24.59  3.61  Female      0   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male      0   Sat  Dinner     3
240       27.18  2.00  Female      1   Sat  Dinner     2
241       22.67  2.00    Male      1   Sat  Dinner     2
242       17.82  1.75    Male      0   Sat  Dinner     2
243       18.78  3.00  Female      0  Thur  Dinner     2

[244 rows x 7 columns]


# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ